version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wallets_db
    ports:
      - "5432:5432"
  wallet_service:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db